[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "AtmosphericEnergizersRework"
description = "Changes Atmospheric Energizers from refilling the Magazine, to refilling the Reserves."
websiteUrl = "https://github.com/Little-Sparroh/AtmosphericEnergizersRework"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/AtmosphericEnergizersRework.dll"
target = "BepInEx/plugins/AtmosphericEnergizersRework.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


